program: main.py #config for wandb sweep

method: random  #bayes

metric:
  name: Train/Loss #Validation/Loss  
  goal: minimize

project: alvis-sweep-loss

parameters:
  lr:
    distribution: log_uniform
    min: 1e-5
    max: 5e-4

  wd:
    distribution: uniform
    min: 0.0
    max: 0.3

  batch_size:
    values: [64, 128, 256]

  epochs:
    values: [30, 40, 50]

#  mixup:
#    values: [True, False]

#  pretrained:
#    values: [True, False]

  optimizer:
    values: ["adamw", "adam", "sgd"]
